### ISSUE TITLE
sh: gmm-boost-silence: command not found when running gmm-aligner.py

### ISSUE THREAD

**Issue by kkawabat** [pykaldi/pykaldi#104]
pykaldi was installed and `python setup.py test` shows that it either skipped or passed all the tests. When I ran the example script examples/alignment/gmm-aligner.py I get the error below.

```
sh: gmm-boost-silence: command not found
ERROR ([5.5.195~1-9daa6]:ExpectToken():io-funcs.cc:203) Failed to read token [started at file position -1], expected <TransitionModel>
ERROR ([5.5.195~1-9daa6]:ExpectToken():io-funcs.cc:203) Failed to read token [started at file position -1], expected <TransitionModel>
WARNING ([5.5.195~1-9daa6]:Close():kaldi-io.cc:515) Pipe gmm-boost-silence --boost=1.0 1 final.mdl - | had nonzero return status 32512
Traceback (most recent call last):
  File "/home/jpadmin/Desktop/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/jpadmin/Desktop/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/jpadmin/Desktop/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/media/jpadmin/c92d86f3-ed84-4b98-b4ca-3d7777aca034/kaldi/pykaldi/examples/alignment/gmm-aligner.py", line 13, in <module>
    self_loop_scale=0.1)
  File "/media/jpadmin/c92d86f3-ed84-4b98-b4ca-3d7777aca034/kaldi/pykaldi/kaldi/alignment.py", line 403, in from_files
    transition_model, acoustic_model = cls.read_model(model_rxfilename)
  File "/media/jpadmin/c92d86f3-ed84-4b98-b4ca-3d7777aca034/kaldi/pykaldi/kaldi/alignment.py", line 369, in read_model
    ki.binary)
RuntimeError: C++ exception: 
```
The strange thing is that I am able to run gmm-boost-slience from the terminal and `which` shows that it's pointing to the kaldi directory inside tools

>/media/jpadmin/c92d86f3-ed84-4b98-b4ca-3d7777aca034/kaldi/pykaldi/tools/kaldi/src/gmmbin/gmm-boost-silence

I have already added KALDI_ROOT to path in bashrc 

```
export KALDI_ROOT='/media/jpadmin/c92d86f3-ed84-4b98-b4ca-3d7777aca034/kaldi/pykaldi/tools/kaldi'
export PATH=$KALDI_ROOT/src/bin:$KALDI_ROOT/tools/openfst/bin:$KALDI_ROOT/src/fstbin:$KALDI_ROOT/src/gmmbin:$KALDI_ROOT/src/featbin:$KALDI_ROOT/src/lmbin:$KALDI_ROOT/src/sgmm2bin:$KALDI_ROOT/src/fgmmbin:$KALDI_ROOT/src/latbin:$PATH
```
I am not sure why gmm-boost-silence is not being found within GmmAligner.from_files()

**Comment by dogancan** [comment]
That is strange indeed. Are you having trouble running the alignment scripts inside example setups such as aspire or zamia?

**Comment by kkawabat** [comment]
I reinstalled pykaldi and now both aspire script and gmm-aligner.py runs. I must have made mistakes during installation somewhere.. thank you for your help!

**Comment by kkawabat** [comment]
The issue was that the terminal in pycharm IDE had different values for path than with the terminal in linux. So while which gmm-boost-silence in linux terminal points to the binfile the one in pycharm did not.
