### ISSUE TITLE
NameError: global name 'EXPANDED' is not defined when calling StdVectorFst.add_arc()

### ISSUE THREAD

**Issue by kkawabat** [pykaldi/pykaldi#106]
```
#sample code
import kaldi.fstext as fst

tmp_fst = fst.StdVectorFst()
state_id = tmp_fst.add_state()
arc = fst.StdArc()
tmp_fst.add_arc(state_id, arc)

```
```
Traceback (most recent call last):
  File "/home/jpadmin/Desktop/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/jpadmin/Desktop/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/jpadmin/Desktop/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/media/jpadmin/c92d86f3-ed84-4b98-b4ca-3d7777aca034/work/kaldi-tools/pykaldi/examples/scripts/gopy/test.py", line 7, in <module>
    tmp_fst.add_arc(state_id, arc)
  File "/media/jpadmin/c92d86f3-ed84-4b98-b4ca-3d7777aca034/work/kaldi-tools/pykaldi/kaldi/fstext/_api.py", line 657, in add_arc
    if not self._valid_state_id(state):
  File "/media/jpadmin/c92d86f3-ed84-4b98-b4ca-3d7777aca034/work/kaldi-tools/pykaldi/kaldi/fstext/_api.py", line 263, in _valid_state_id
    if not self._properties(EXPANDED, True):
NameError: global name 'EXPANDED' is not defined

```
I think the issue is that line 262 of fstext's _api.py 
` if not self._properties(EXPANDED, True):`
should be
` if not self._properties(_props.EXPANDED, True):`

**Comment by dogancan** [comment]
Thanks for the report. You're right. It seems I missed that one when refactoring the fstext package. Would you like to open pull request for the bugfix?

**Comment by dogancan** [comment]
I am closing this but feel free to reopen if you continue to have problems.
