### ISSUE TITLE
How do I install props.references? 

### ISSUE THREAD

**Issue by diffLocks16** [pykaldi/pykaldi#149]
```
(env) Lukas-MacBook-Pro:pykaldi lukaguinan$ sudo easy_install pymodels
Searching for pymodels
Reading https://pypi.org/simple/pymodels/
Downloading https://files.pythonhosted.org/packages/0d/35/fefe105db2b3c7b1641ac52133f97f04caf7552408975aa2ea6768b7e554/pymodels-0.18.3.tar.gz#sha256=7f74804f1fef80ea07ade5cb291e7ecfa19287f8ab6b1f3cf70b7ca8cd635d16
Best match: pymodels 0.18.3
Processing pymodels-0.18.3.tar.gz
Writing /tmp/easy_install-seekr57y/pymodels-0.18.3/setup.cfg
Running pymodels-0.18.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-seekr57y/pymodels-0.18.3/egg-dist-tmp-h7tyqsvh
Traceback (most recent call last):
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-seekr57y/pymodels-0.18.3/setup.py", line 25, in <module>
  File "/tmp/easy_install-seekr57y/pymodels-0.18.3/pymodels/__init__.py", line 25, in <module>
ModuleNotFoundError: No module named 'props.references'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lukaguinan/pykaldi/env/bin/easy_install", line 11, in <module>
    load_entry_point('setuptools==41.0.1', 'console_scripts', 'easy_install')()
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 2316, in main
    **kw
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/lukaguinan/pykaldi/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-seekr57y/pymodels-0.18.3/setup.py", line 25, in <module>
  File "/tmp/easy_install-seekr57y/pymodels-0.18.3/pymodels/__init__.py", line 25, in <module>
ModuleNotFoundError: No module named 'props.references'
```
I built the pykaldi package doing everything as it says however when I tried to run the offline recognition code I realised packages were missing so I installed them manually. So far I have done pytorch but can't do models because more packages are missing...specifically `props.references`. How can I install this one?

**Comment by vrmpx** [comment]
Hello,
I don't know about the pymodels package and we don't know of any pretrained pytorch models compatible with kaldi. You might be able to train such pytorch models using the new pykaldi2 toolkit.

**Comment by diffLocks16** [comment]
Ok, instead could you point me in the direction of detailed install instructions for the offline kaldi asr recognition? The ones on your Github page aren't clear. Thank you
