### ISSUE TITLE
ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'

### ISSUE THREAD

**Issue by chrisspen** [pykaldi/pykaldi#190]
The [install from source](https://github.com/pykaldi/pykaldi#from-source) instructions do not seem to work on Ubuntu 18.04.

I ran:

    virtualenv -p python3.6 .env
    . .env/bin/activate
    cd tools
    ./install_protobuf.sh
    ./install_clif.sh
    ./install_kaldi.sh
    cd ..
    python setup.py install

And everything seemed to run without error, but if I import anything from kaldi I get an error:

    $ python
    Python 3.6.8 (default, Dec 24 2018, 19:24:27) 
    [GCC 5.4.0 20160609] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from kaldi.asr import NnetLatticeFasterRecognizer
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/chris/git/pykaldi/kaldi/__init__.py", line 14, in <module>
        from . import base
      File "/home/chris/git/pykaldi/kaldi/base/__init__.py", line 1, in <module>
        from ._kaldi_error import *
    ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'

I get the same error if I try the conda install method too.

**Comment by vrmpx** [comment]
Oh I replied to #188 before seeing this one.
Yeah the problem is that your `python` picks on the `__init__` from the source folder.
Just run `python` outside the `pykaldi` folder and the import should go through.
