### ISSUE TITLE
MatrixWriter cannot write CompressedMatrix to file due to lack of CompressedMatrix.size() function

### ISSUE THREAD

**Issue by kkawabat** [pykaldi/pykaldi#199]
When writing a compressedMatrix to file:

```
import kaldi

feats_wspecifier = 'ark,scp:path\to\output\test_mtx.ark,path\to\output\test_mtx.scp'

with kaldi.util.table.MatrixWriter(feats_wspecifier) as writer:
    mtx = kaldi.matrix.Matrix([[1,2],[2,2]])
    writer['test_key'] = CompressedMatrix.new(mtx)
```

I get the error: 

> Traceback (most recent call last):
>   File "/home/kan/.PyCharmCE2019.3/config/scratches/mfcc_tests.py", line 65, in compute_mfcc_feats
>     writer[key] = CompressedMatrix.new(feats)
>   File "/home/kan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pykaldi-0.1.2-py3.7-linux-x86_64.egg/kaldi/util/table.py", line 721, in __setitem__
>     self.write(key, value)
>   File "/home/kan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pykaldi-0.1.2-py3.7-linux-x86_64.egg/kaldi/util/table.py", line 825, in write
>     super(MatrixWriter, self).write(key, _matrix.Matrix(value))
>   File "/home/kan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pykaldi-0.1.2-py3.7-linux-x86_64.egg/kaldi/matrix/_matrix.py", line 1314, in __init__
>     self.copy_(obj)
>   File "/home/kan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pykaldi-0.1.2-py3.7-linux-x86_64.egg/kaldi/matrix/_matrix.py", line 744, in copy_
>     if self.size() != src.size():
> AttributeError: 'kaldi.matrix._compressed_matrix.CompressedMatrix' object has no attribute 'size'

I was able to bypass this by modifying line 744 in [_matrix.py](https://github.com/pykaldi/pykaldi/blob/249963c2cb57d92c0027bb958280dcf8e408462a/kaldi/matrix/_matrix.py#L744) to:

```
if self.num_cols != src.num_cols or self.num_rows != src.num_rows:
    raise ValueError("Cannot copy matrix with dimensions {s[0]}x{s[1]} "
                     "into matrix with dimensions {d[0]}x{d[1]}"
                     .format(s=(src.num_cols, src.num_rows), d=self.size()))
```

Although this works the resulting file seems to be removing the compression as resulting ark file is 4x larger than with kaldi's  'copy-feats --compress=true ark:- ark:-' call

**Comment by kkawabat** [comment]
I was able to write compressedMatrix to file by adding the following class in kaldi/util/table.py 

```
class CompressedMatrixWriter(_WriterBase, _kaldi_table.CompressedMatrixWriter):
    """Table writer for CompressedMatrix."""
    def write(self, key, value):
        """Writes the `(key, value)` pair to the table.

        This method is provided for compatibility with the C++ API only;
        most users should use the Pythonic API.

        Overrides write to accept both CompressedMatrix

        Args:
            key (str): The key.
            value: The value.
        """
        if not isinstance(value, _matrix.compressed.CompressedMatrix):
            raise ValueError("value needs to be a CompressedMatrix")
        super(CompressedMatrixWriter, self).write(key, value)
```

and changing the writer to 

```with kaldi.util.table.CompressedMatrixWriter(feats_wspecifier) as writer:```
