### ISSUE TITLE
Minimize() error after verify() returns true

### ISSUE THREAD

**Issue by QIU-Shuo** [pykaldi/pykaldi#203]
Hi, here's a minimal code to replicate this problem

```
import kaldi.fstext as fst
from kaldi.fstext import  StdVectorFst, StdArc, TropicalWeight
subg = StdVectorFst()

init = subg.add_state()
subg.set_start(init)
s0 = subg.add_state()
subg.add_arc(init, StdArc(1, 1, TropicalWeight.one(), s0))
subg.set_final(s0, TropicalWeight.one())
print(subg.verify())
subg = fst.determinize(subg)
subg.minimize()
````
Results in 
```
True
Traceback (most recent call last):
  File "/ssd4/exec/qiushuo/package/miniconda3/envs/kaldi/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-4711631d65ff>", line 12, in <module>
    subg.minimize()
  File "/ssd4/exec/qiushuo/package/miniconda3/envs/kaldi/lib/python3.7/site-packages/kaldi/fstext/_api.py", line 886, in minimize
    self._ops.minimize(self, delta, allow_nondet)
TypeError: minimize() argument sfst is not valid for ::fst::MutableFst< ::fst::ArcTpl< ::fst::TropicalWeightTpl<float> > > * (float instance given): expecting kaldi.fstext._mutable_fst.StdMutableFst instance, got float instance
```

**Comment by QIU-Shuo** [comment]
A work-around: save the intermediate fst to disk, then using bash command to perform determinize, minimize will perform as expected
