### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by mpattnaik97** [pykaldi/pykaldi#220]
After following the readme, the command "python setup.py install" finished successfully. But when I ran "python setup.py test" it is giving me the following output!

`running pytest
Searching for pytest
Best match: pytest 5.4.3
Processing pytest-5.4.3-py2.7.egg

Using /home/mitravind/pykaldi/.eggs/pytest-5.4.3-py2.7.egg
Searching for importlib-metadata>=0.12
Best match: importlib-metadata 1.6.1
Processing importlib_metadata-1.6.1-py2.7.egg

Using /home/mitravind/pykaldi/.eggs/importlib_metadata-1.6.1-py2.7.egg
Searching for pathlib2>=2.2.0
Best match: pathlib2 2.3.5
Processing pathlib2-2.3.5-py2.7.egg

Using /home/mitravind/pykaldi/.eggs/pathlib2-2.3.5-py2.7.egg
Searching for wcwidth
Best match: wcwidth 0.2.5
Processing wcwidth-0.2.5-py2.7.egg

Using /home/mitravind/pykaldi/.eggs/wcwidth-0.2.5-py2.7.egg
Searching for pluggy<1.0,>=0.12
Best match: pluggy 0.13.1
Processing pluggy-0.13.1-py2.7.egg

Using /home/mitravind/pykaldi/.eggs/pluggy-0.13.1-py2.7.egg
Searching for more-itertools>=4.0.0
Reading https://pypi.org/simple/more-itertools/
Downloading https://files.pythonhosted.org/packages/67/4a/16cb3acf64709eb0164e49ba463a42dc45366995848c4f0cf770f57b8120/more-itertools-8.4.0.tar.gz#sha256=68c70cc7167bdf5c7c9d8f6954a7837089c6a36bf565383919bb595efb8a17e5
Best match: more-itertools 8.4.0
Processing more-itertools-8.4.0.tar.gz
Writing /tmp/easy_install-YOHGvb/more-itertools-8.4.0/setup.cfg
Running more-itertools-8.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-YOHGvb/more-itertools-8.4.0/egg-dist-tmp-aHisR1
Traceback (most recent call last):
  File "setup.py", line 353, in <module>
    test_suite='tests')
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/mitravind/pykaldi/.eggs/pytest_runner-5.2-py2.7.egg/ptr.py", line 202, in run
    installed_dists = self.install_dists(dist)
  File "/home/mitravind/pykaldi/.eggs/pytest_runner-5.2-py2.7.egg/ptr.py", line 153, in install_dists
    orig.test.install_dists(dist), self.install_extra_dists(dist)
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/command/test.py", line 209, in install_dists
    tr_d = dist.fetch_build_eggs(dist.tests_require or [])
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
    replace_conflicting=True,
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/home/mitravind/pykaldi/.eggs/pytest_runner-5.2-py2.7.egg/ptr.py", line 84, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/mitravind/pykaldi_env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-YOHGvb/more-itertools-8.4.0/setup.py", line 5, in <module>
    import os
  File "/tmp/easy_install-YOHGvb/more-itertools-8.4.0/more_itertools/__init__.py", line 1, in <module>
  File "/tmp/easy_install-YOHGvb/more-itertools-8.4.0/more_itertools/more.py", line 161
    ) from e
         ^
SyntaxError: invalid syntax`

**Comment by bmilde** [comment]
I'm really not sure what went wrong here, our github build completes successfully on Python 2.7 including the tests.

Please try our latest version and report back if you still see this error. Otherwise we also release whl files that might make using PyKaldi easier.
