### ISSUE TITLE
Intall error

### ISSUE THREAD

**Issue by yjw123456** [pykaldi/pykaldi#233]
Hi guys!

I encountered this issue after the conda intallation.

######################################################################################
from kaldi import asr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/home/tomasyu/anaconda3/envs/pychain/lib/python3.7/site-packages/kaldi/asr.py", line 13, in <module>
    from . import cudamatrix as _cumatrix
  File "/data/home/tomasyu/anaconda3/envs/pychain/lib/python3.7/site-packages/kaldi/cudamatrix/__init__.py", line 15, in <module>
    from ._cu_sparse_matrix import *
ImportError: /data/home/tomasyu/anaconda3/envs/pychain/lib/python3.7/site-packages/kaldi/cudamatrix/../matrix/_sparse_matrix.so: undefined symbol: _ZN5kaldi12SparseMatrixIfEC1ERKNS_10MatrixBaseIfEE
######################################################################################

Can anyone give me some clues?

**Comment by bmilde** [comment]
Conda build is currently out of date and sadly does not have a maintainer anymore.

But we recently released whl files that you can use with virtual environments / pip.
