### ISSUE TITLE
How to create a portable wheel?

### ISSUE THREAD

**Issue by srdecny** [pykaldi/pykaldi#320]
I created a pykaldi wheel by following the instructions at https://github.com/pykaldi/pykaldi?tab=readme-ov-file#step-2-install-dependencies which results in a .whl file. The wheel works fine when installed on the machine where kaldi was compiled. However, when installing the wheel on another machine (such as a docker container), importing kaldi no longer works:

```
root@88d7b7ab862f:/code# python3 -c "import kaldi"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.12/dist-packages/kaldi/__init__.py", line 14, in <module>
    from . import base
  File "/usr/local/lib/python3.12/dist-packages/kaldi/base/__init__.py", line 1, in <module>
    from ._kaldi_error import *
ImportError: libkaldi-base.so: cannot open shared object file: No such file or directory
```

This is because the wheel doesn't contain the `libkaldi-base.so` file, which is located at `kaldi/src/lib/libkaldi-base.so` in the kaldi repository.

Is there a way how to include these .so files and other dynamically linked dependencies into the wheel to avoid these issues?

**Comment by srdecny** [comment]
https://github.com/pykaldi/pykaldi/issues/261#issuecomment-1961276721 is relevant here

**Comment by bmilde** [comment]
Pull requests to get this automated with a build script or setup.py would be very welcome :)
