### ISSUE TITLE
CLIF installation failing due to compatibility issue with Protobuf

### ISSUE THREAD

**Issue by alexforever86** [pykaldi/pykaldi#34]
`"$MAKE_OR_NINJA" "${MAKE_PARALLELISM[@]}" clif-matcher clif_python_utils_proto_util` line 144 in `pykaldi/install_clif.sh` failing with the following error.

```
[1785/1788] Generating proto_util.cc, proto_util.h, proto_util.init.cc
FAILED: tools/clif/python/utils/proto_util.cc tools/clif/python/utils/proto_util.h tools/clif/python/utils/proto_util.init.cc 
cd /pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils && PYTHONPATH=/pykaldi/tools/clif_backend/build_matcher/tools:/pykaldi/tools/clif_backend/llvm/tools /opt/conda/bin/python /pykaldi/tools/clif_backend/llvm/tools/clif/pyclif.py -p/pykaldi/tools/clif_backend/llvm/tools/clif/python/types.h -c/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils/proto_util.cc -g/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils/proto_util.h -i/pykaldi/tools/clif_backend/build_matcher/tools/clif/python/utils/proto_util.init.cc -I/pykaldi/tools/clif_backend/llvm/tools -I/pykaldi/tools/clif_backend/build_matcher/tools --modname=clif.python.utils.proto_util --matcher_bin=/pykaldi/tools/clif_backend/build_matcher/bin/clif-matcher "-f-I/opt/conda/include/python3.6m -I/pykaldi/tools/clif_backend/llvm/tools -I/pykaldi/tools/clif_backend/build_matcher/tools -I/pykaldi/tools/protobuf/include -std=c++11 " /pykaldi/tools/clif_backend/llvm/tools/clif/python/utils/proto_util.clif
Traceback (most recent call last):
  File "/pykaldi/tools/clif_backend/llvm/tools/clif/pyclif.py", line 37, in <module>
    from clif.protos import ast_pb2
  File "/pykaldi/tools/clif_backend/build_matcher/tools/clif/protos/ast_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\tast.proto\x12\x0b\x63lif.protos\"\xdf\x01\n\x03\x41ST\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x19\n\x11usertype_includes\x18\x02 \x03(\t\x12 \n\x05\x64\x65\x63ls\x18\x03 \x03(\x0b\x32\x11.clif.protos.Decl\x12\x12\n\nextra_init\x18\x04 \x03(\t\x12\x18\n\x10\x63\x61tch_exceptions\x18\x05 \x01(\x08\x12&\n\x08typemaps\x18\x06 \x03(\x0b\x32\x14.clif.protos.Typemap\x12\"\n\x06macros\x18\x07 \x03(\x0b\x32\x12.clif.protos.Macro\x12\x11\n\tdocstring\x18\x08 \x01(\t\"\xc9\x03\n\x04\x44\x65\x63l\x12(\n\x08\x64\x65\x63ltype\x18\x01 \x01(\x0e\x32\x16.clif.protos.Decl.Type\x12(\n\x06\x63lass_\x18\n \x01(\x0b\x32\x16.clif.protos.ClassDeclH\x00\x12%\n\x04\x65num\x18\x0b \x01(\x0b\x32\x15.clif.protos.EnumDeclH\x00\x12#\n\x03var\x18\x0c \x01(\x0b\x32\x14.clif.protos.VarDeclH\x00\x12\'\n\x05\x63onst\x18\r \x01(\x0b\x32\x16.clif.protos.ConstDeclH\x00\x12%\n\x04\x66unc\x18\x0e \x01(\x0b\x32\x15.clif.protos.FuncDeclH\x00\x12)\n\x05\x66\x64\x65\x63l\x18\x0f \x01(\x0b\x32\x18.clif.protos.ForwardDeclH\x00\x12\x10\n\x08\x63pp_file\x18\x02 \x01(\t\x12\x11\n\tnot_found\x18\x03 \x01(\t\x12\x13\n\x0bline_number\x18\x04 \x01(\x05\x12\x12\n\nnamespace_\x18\x05 \x01(\t\"P\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04\x45NUM\x10\x01\x12\x07\n\x03VAR\x10\x02\x12\t\n\x05\x43ONST\x10\x03\x12\x08\n\x04\x46UNC\x10\x04\x12\x08\n\x04TYPE\x10\x05\x12\t\n\x05\x43LASS\x10\x06\x42\x06\n\x04\x64\x65\x63l\"\xdb\x03\n\tClassDecl\x12\x1f\n\x04name\x18\x01 \x01(\x0b\x32\x11.clif.protos.Name\x12 \n\x05\x62\x61ses\x18\x02 \x03(\x0b\x32\x11.clif.protos.Name\x12\"\n\x07members\x18\x03 \x03(\x0b\x32\x11.clif.protos.Decl\x12\r\n\x05\x66inal\x18\x04 \x01(\x08\x12\x12\n\x06shared\x18\x05 \x01(\x08\x42\x02\x18\x01\x12\x1e\n\x10\x63pp_has_def_ctor\x18\x06 \x01(\x08:\x04true\x12\x1f\n\x17\x63pp_has_trivial_defctor\x18\x0c \x01(\x08\x12\x1c\n\x14\x63pp_has_trivial_dtor\x18\r \x01(\x08\x12!\n\x13\x63pp_has_public_dtor\x18\t \x01(\x08:\x04true\x12\x12\n\nasync_dtor\x18\n \x01(\x08\x12\x1a\n\x0c\x63pp_copyable\x18\x07 \x01(\x08:\x04true\x12\x14\n\x0c\x63pp_abstract\x18\x08 \x01(\x08\x12.\n\tcpp_bases\x18\x0b \x03(\x0b\x32\x1b.clif.protos.ClassDecl.Base\x12\x11\n\tdocstring\x18\x0e \x01(\t\x1a\x39\n\x04\x42\x61se\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\"\x84\x01\n\x08\x45numDecl\x12\x1f\n\x04name\x18\x01 \x01(\x0b\x32\x11.clif.protos.Name\x12\"\n\x07members\x18\x02 \x03(\x0b\x32\x11.clif.protos.Name\x12\x12\n\nenum_class\x18\x03 \x01(\x08\x12\x1f\n\x04item\x18\x04 \x01(\x0b\x32\x11.clif.protos.Type\"\x9b\x01\n\x07VarDecl\x12\x1f\n\x04name\x18\x01 \x01(\x0b\x32\x11.clif.protos.Name\x12\x1f\n\x04type\x18\x02 \x01(\x0b\x32\x11.clif.protos.Type\x12&\n\x07\x63pp_get\x18\x03 \x01(\x0b\x32\x15.clif.protos.FuncDecl\x12&\n\x07\x63pp_set\x18\x04 \x01(\x0b\x32\x15.clif.protos.FuncDecl\"\\\n\tConstDecl\x12\x1f\n\x04name\x18\x01 \x01(\x0b\x32\x11.clif.protos.Name\x12\x1f\n\x04type\x18\x02 \x01(\x0b\x32\x11.clif.protos.Type\x12\r\n\x05value\x18\x03 \x01(\t\"|\n\tParamDecl\x12\x1f\n\x04name\x18\x01 \x01(\x0b\x32\x11.clif.protos.Name\x12\x1f\n\x04type\x18\x02 \x01(\x0b\x32\x11.clif.protos.Type\x12\x16\n\x0e\x63pp_exact_type\x18\x04 \x01(\t\x12\x15\n\rdefault_value\x18\x03 \x01(\t\"\x98\x03\n\x08\x46uncDecl\x12\x1f\n\x04name\x18\x01 \x01(\x0b\x32\x11.clif.protos.Name\x12&\n\x06params\x18\x02 \x03(\x0b\x32\x16.clif.protos.ParamDecl\x12\'\n\x07returns\x18\x03 \x03(\x0b\x32\x16.clif.protos.ParamDecl\x12\'\n\x07\x65xcepts\x18\x04 \x03(\x0b\x32\x16.clif.protos.Exception\x12\x10\n\x08postproc\x18\x05 \x01(\t\x12\x13\n\x0b\x63onstructor\x18\x12 \x01(\x08\x12\x13\n\x0b\x63lassmethod\x18\x0b \x01(\x08\x12\x13\n\x0bpy_keep_gil\x18\x0c \x01(\x08\x12\x0f\n\x07virtual\x18\x0f \x01(\x08\x12\x1b\n\x13ignore_return_value\x18\x10 \x01(\x08\x12\x17\n\x0f\x63pp_void_return\x18\r \x01(\x08\x12\x14\n\x0c\x63pp_noexcept\x18\x0e \x01(\x08\x12\x16\n\x0e\x63pp_opfunction\x18\x11 \x01(\x08\x12\x18\n\x10\x63pp_const_method\x18\x13 \x01(\x08\x12\x11\n\tdocstring\x18\x14 \x01(\t\".\n\x0b\x46orwardDecl\x12\x1f\n\x04name\x18\x01 \x01(\x0b\x32\x11.clif.protos.Name\"(\n\x04Name\x12\x0e\n\x06native\x18\x01 \x01(\t\x12\x10\n\x08\x63pp_name\x18\x02 \x01(\t\"\xc5\x02\n\x04Type\x12\x11\n\tlang_type\x18\x01 \x01(\t\x12\x10\n\x08\x63pp_type\x18\x02 \x01(\t\x12!\n\x06params\x18\x03 \x03(\x0b\x32\x11.clif.protos.Type\x12\'\n\x08\x63\x61llable\x18\x04 \x01(\x0b\x32\x15.clif.protos.FuncDecl\x12\x1e\n\x10\x63pp_has_def_ctor\x18\x05 \x01(\x08:\x04true\x12\x1a\n\x0c\x63pp_copyable\x18\x06 \x01(\x08:\x04true\x12\x17\n\x0f\x63pp_raw_pointer\x18\x07 \x01(\x08\x12\x1c\n\x14\x63pp_toptr_conversion\x18\x08 \x01(\x08\x12 \n\x18\x63pp_touniqptr_conversion\x18\x0b \x01(\x08\x12\x14\n\x0c\x63pp_abstract\x18\t \x01(\x08\x12!\n\x13\x63pp_has_public_dtor\x18\n \x01(\x08:\x04true\"*\n\tException\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63hecked\x18\x02 \x01(\x08\"3\n\tTypeTable\x12&\n\x08typemaps\x18\x01 \x03(\x0b\x32\x14.clif.protos.Typemap\"F\n\x07Typemap\x12\x11\n\tlang_type\x18\x01 \x01(\t\x12\x10\n\x08\x63pp_type\x18\x02 \x03(\t\x12\x16\n\x0epostconversion\x18\x03 \x01(\t\")\n\x05Macro\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\x0c')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
ninja: build stopped: subcommand failed.
```

In file `/pykaldi/tools/clif_backend/build_matcher/tools/clif/protos/ast_pb2.py`, function call includes a parameter `serialized_options=None`, which is recently added to Protobuf.
https://github.com/google/protobuf/commit/0400cca3236de1ca303af38bf81eab332d042b7c#diff-d6de91caf3b3a819abb247fae7f62938

```
from google.protobuf import descriptor as _descriptor

DESCRIPTOR = _descriptor.FileDescriptor(
  name='ast.proto',
  package='clif.protos',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\tast.......
....
```

**Comment by alexforever86** [comment]
Strange that protoc command gives an earlier version.
```
protoc --version
libprotoc 3.5.1
```

**Comment by alexforever86** [comment]
The version mismatch is due to https://github.com/google/protobuf/issues/4491

**Comment by dogancan** [comment]
@alexforever86 Is this issue specific to pykaldi fork of CLIF? Can you build vanilla CLIF from the [upstream repo](https://github.com/google/clif) without issues?

**Comment by alexforever86** [comment]
@dogancan I have only tried with `pykaldi` branch. I will check `google/clif` and update shortly.

**Comment by alexforever86** [comment]
@dogancan I don't think this is due to any issues with pykaldi repo of kaldi as there aren't much difference. I will try this tomorrow. For now, I made it work with using an earlier version (350b135e233ba607e5cbc08a4f8b824d20f4b9c9) of Protobuf.
