### ISSUE TITLE
Runtime Error using nnet3 decoder with Cuda

### ISSUE THREAD

**Issue by mollynatsu** [pykaldi/pykaldi#42]
Hi,

I got a Runtime error when running a nnet3 based decoder using the GPU. My model works fine running on a CPU, but once I set ```CuDevice.instantiate().select_gpu_id('yes')''', the following error occurs:

```
WARNING ([5.4.45~1-6e639]:SelectGpuId():cu-device.cc:192) Not in compute-exclusive mode.  Suggestion: use 'nvidia-smi -c 3' to set compute exclusive mode
LOG ([5.4.45~1-6e639]:SelectGpuIdAuto():cu-device.cc:311) Selecting from 1 GPUs
LOG ([5.4.45~1-6e639]:SelectGpuIdAuto():cu-device.cc:326) cudaSetDevice(0): GeForce GTX 1080 Ti	free:10734M, used:430M, total:11164M, free/total:0.961468
LOG ([5.4.45~1-6e639]:SelectGpuIdAuto():cu-device.cc:375) Trying to select device: 0 (automatically), mem_ratio: 0.961468
LOG ([5.4.45~1-6e639]:SelectGpuIdAuto():cu-device.cc:394) Success selecting device 0 free mem ratio: 0.961468
LOG ([5.4.45~1-6e639]:FinalizeActiveGpu():cu-device.cc:243) The active GPU is [0]: GeForce GTX 1080 Ti	free:10670M, used:494M, total:11164M, free/total:0.955735 version 6.1
audio length: 0.760000 s
ERROR ([5.4.45~1-6e639]:RemoveLeastRecentlyUsed():cu-allocator.cc:349) cudaError_t 77 : "an illegal memory access was encountered" returned from 'cudaFree(p.first.pointer)'
WARNING ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:435) Printing some background info since error was detected
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:436) matrix m1(1, 100), m2(70, 40), m3(70, 300), m4(66, 1536), m5(64, 1536), m6(62, 1536), m7(56, 1536), m8(50, 512), m9(50, 5686), m10(50, 5686)
# The following show how matrices correspond to network-nodes and
# cindex-ids.  Format is: matrix = <node-id>.[value|deriv][ <list-of-cindex-ids> ]
# where a cindex-id is written as (n,t[,x]) but ranges of t values are compressed
# so we write (n, tfirst:tlast).
m1 == value: ivector[(0,0)]
m2 == value: input[(0,-13:56)]
m3 == value: tdnn1.affine_input[(0,-11:54), (0,-2147483648), (0,-2147483648), (0,-2147483648), (0,-2147483648)]
m4 == value: tdnn2.affine_input[(0,-10:53), (0,-2147483648), (0,-2147483648)]
m5 == value: tdnn3.affine_input[(0,-9:52), (0,-2147483648), (0,-2147483648)]
m6 == value: tdnn4.affine_input[(0,-6:49), (0,-2147483648), (0,-2147483648), (0,-2147483648), (0,-2147483648), (0,-2147483648), (0,-2147483648)]
m7 == value: tdnn5.affine_input[(0,0:49), (0,-2147483648), (0,-2147483648), (0,-2147483648), (0,-2147483648), (0,-2147483648), (0,-2147483648)]
m8 == value: tdnn5.affine[(0,0:49)]
m9 == value: output.affine[(0,0:49)]
m10 == value: output.log-softmax[(0,0:49)]
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c0: m1 = user input [for node: 'ivector']
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c1: m2 = user input [for node: 'input']
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c2: [no-op-permanent]
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c3: m3 = undefined(70,300)
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c4: m3(0:69, 0:39) = m2
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c5: m3(0:65, 40:79) = m2(1:66, 0:39)
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c6: m3(0:65, 80:119) = m2(2:67, 0:39)
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c7: m3(0:65, 120:159) = m2(3:68, 0:39)
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c8: m3(0:65, 160:199) = m2(4:69, 0:39)
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c9: m2 = []
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c10: m3(0:65, 200:299).CopyRows(1, m1[0x66])
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c11: m1 = []
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c12: m4 = undefined(66,1536)
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c13: lda.tdnn1.affine.Propagate(NULL, m3(0:65, 0:299), &m4(0:65, 0:511))
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c14: m3 = []
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c15: tdnn1.relu.Propagate(NULL, m4(0:65, 0:511), &m4(0:65, 0:511))
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c16: m4(0:63, 512:1023) = m4(1:64, 0:511)
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c17: m4(0:63, 1024:1535) = m4(2:65, 0:511)
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c18: m5 = undefined(64,1536)
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c19: tdnn1.batchnorm.tdnn2.affine.Propagate(NULL, m4(0:63, 0:1535), &m5(0:63, 0:511))
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c20: m4 = []
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c21: tdnn2.relu.Propagate(NULL, m5(0:63, 0:511), &m5(0:63, 0:511))
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c22: m5(0:61, 512:1023) = m5(1:62, 0:511)
LOG ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:438) c23: m5(0:61, 1024:1535) = m5(2:63, 0:511)
ERROR ([5.4.45~1-6e639]:ExecuteCommand():nnet-compute.cc:442) Error running command c24: m6 = undefined(62,1536)
Traceback (most recent call last):
  File "scoreit_pykaldi.py", line 102, in <module>
    kaldi_model=kaldi_model)
  File "scoreit_pykaldi.py", line 37, in run_pykaldi
    kaldi_model.nnet3_decode(utterance)
  File "/home/eflsd/dev/Projects/librispeech/dev/pyscripts/interface/KaldiModel.py", line 161, in nnet3_decode
    self.decoder.decode(nnet_decodable)
RuntimeError: C++ exception: 
ERROR ([5.4.45~1-6e639]:Free():cu-allocator.cc:285) Attempt to free CUDA memory pointer that was not allocated: 0x55c38fd02d90
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Aborted (core dumped)
'''

Do you know why this is happening?

**Comment by vrmpx** [comment]
Hello @mollynatsu,
If you can provide a minimum working example, I can take look into this.
