### ISSUE TITLE
nnet3 online with endpointing fails

### ISSUE THREAD

**Issue by francoishernandez** [pykaldi/pykaldi#68]
Hi @dogancan 
We tried to run your example nnet3 online decoding script.
The first two methods work, but the third one with endpointing fails with the following error:
```
ASSERTION_FAILED ([5.4.49~2-5eb7]:EnsureFrameIsComputed():nnet3/decodable-online-looped.h:94) : 'subsampled_frame >= current_log_post_subsampled_offset_ && "Frames must be accessed in order."' 
Traceback (most recent call last):
  File "./nnet3-online-recognizer.py", line 121, in <module>
    asr.advance_decoding()
  File "/mosesgpu-184-storage/kaldi_tools/online/env3/lib/python3.6/site-packages/pykaldi-0.0.9-py3.6-linux-x86_64.egg/kaldi/asr.py", line 1202, in advance_decoding
    self.decoder.advance_decoding(self._decodable, max_num_frames)
RuntimeError: C++ exception: 
WARNING ([5.4.49~2-5eb7]:~HashList():util/hash-list-inl.h:117) Possible memory leak: 18431 != 18432: you might have forgotten to call Delete on some Elems
```
We've been playing around a bit with the `NnetLatticeFasterOnlineRecognizer` class and we noticed the following behaviour:
- when we call `finalize_decoding()` and then `init_decoding()` it fails with the same error as soon as we try to `advance_decoding()` with new features;
- the pipe `finalize_decoding()` `get_output()` `init_decoding()` works, but the whole context since the beginning of the decoding remains, whereas we thought it would 'reset' the utterance by calling `finalize_decoding()`.
Is it possible with the existing code and wrappers to 'reset' the utterance inside the same `NnetLatticeFasterOnlineRecognizer` object?

**Comment by dogancan** [comment]
Thanks for the report. This was my bad. I had thought reinitializing the decoder would be enough but it turns out we also need to reset the feature pipeline since the decoder starts counting the frames from 0 after the `init_decoding` call.
